### PR TITLE
30 new function label converter

### LINKED ISSUE #30: [NEW function] label_converter
## Functionality
- [x] create a label in specified format from jaar, soort, labeltype, jaar
- [x] export options should be `c("eloket", "labo")`. default eloket.
- [x] if label allready in correct format include as is in list
- [x] if label not in correct format try to conform else NA

## Checklist
- [x] kopieer [label_converter.R](https://github.com/inbo/fis-projecten/blob/master/Functions/label_converter.R) sla het R bestand op onder `./R` 
- [x] voorzie een functie titel met `#'` op regel 1 van je script
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [x] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [x] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [x] voer `roxygen2::roxygenise()` uit in de console
- [x] voer `devtools::check()` uit in de console
- [x] los eventuele errors, warnings en notes<sup>1</sup> op
- [x] increment versie dmv `usethis::use_version(which = "minor")`<sup>2</sup>
- [x] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

*<sup>2</sup>als je meer dan 5 functies en/of datasets in één pull request veranderd hebt gebruik: `usethis::use_version(which = "major")`*

### PR DESCRIPTION
**Pull request by SanderDevisscher**
fixes #30

### CODE REVIEW

**Review by soriadelva — DISMISSED** [review]
The code itself works well but I have a few comments that may be addressed:

- When labeltype is hardcoded, uppercase letters are not accepted, see: https://github.com/inbo/fistools/blob/f954789e8f2b8df5128a251be19e3c001bae521e/R/label_converter.R#L45-L50 which throws an error, because only the lowercase reekits is accepted. 

- The df of the final example cannot be constructed because column labeltype is not present in initial dataset labels, throwing an error on this line: https://github.com/inbo/fistools/blob/f954789e8f2b8df5128a251be19e3c001bae521e/R/label_converter.R#L57
- Not that important, but I was wondering whether it would be better to place the function parameters in English (i.e., labelnumber instead of labelnummer, species_column instead of soort_column,...)
- Also not that important but it may be nice to add a line after each warning that involves checking, saying that the check passed. e.g., after this warning: `1: In label_converter(df, "id", "labelnummer", "REE", "labeltype",  :
  soort_column: REE is not a column of input >> checking if it's an allowed species` there could be a line saying `check passed 🎉 `

**Review by soriadelva — COMMENTED** [review]
When I try to load the function, it seems to get stuck after line 136, not sure what is happening but it may be good to check if this also happens for you @SanderDevisscher

**Comment by SanderDevisscher** [comment]
@soriadelva how do you mean gets stuck ?

**Comment by SanderDevisscher** [comment]
> The code itself works well but I have a few comments that may be addressed:
> 
> * When labeltype is hardcoded, uppercase letters are not accepted, see: https://github.com/inbo/fistools/blob/f954789e8f2b8df5128a251be19e3c001bae521e/R/label_converter.R#L45-L50
>    which throws an error, because only the lowercase reekits is accepted.

Fixed 🥳 

> * The df of the final example cannot be constructed because column labeltype is not present in initial dataset labels, throwing an error on this line: https://github.com/inbo/fistools/blob/f954789e8f2b8df5128a251be19e3c001bae521e/R/label_converter.R#L57

Added a remark in the example. You should run an example which results in less than 1000 labels first (e.a. example 1)

> * Not that important, but I was wondering whether it would be better to place the function parameters in English (i.e., labelnumber instead of labelnummer, species_column instead of soort_column,...)

Not implemented since function will be used by us only. I could translate everything to dutch if prefered (as a new issue)

> * Also not that important but it may be nice to add a line after each warning that involves checking, saying that the check passed. e.g., after this warning: `1: In label_converter(df, "id", "labelnummer", "REE", "labeltype",  : soort_column: REE is not a column of input >> checking if it's an allowed species` there could be a line saying `check passed 🎉 `

Implemented, whenever the function checks something and the check is succesfully completed  `check passed 🎉` is printed.

Additional fixes and enhancements:
1. I've implemented some logic to bypass the labeltype logic when labeltype_column is not provided and not needed (only needed with soort = "ree")
2. I've added a collapsed list of the allowed species and labeltypes to the error message you get when they are not allowed.

**Comment by soriadelva** [comment]
> @soriadelva how do you mean gets stuck ?

it's weird, when I just run the function in the code itself it keeps on getting stuck at that same line, like this:
stuck
But if I select the whole code with ctrl + A and then run it, it seems to be fine 🤔

**Review by soriadelva — APPROVED** [review]

**Review by soriadelva — APPROVED** [review]

**Pull request merged**
